name: Funksjonsønske
description: Foreslå en ny funksjon eller forbedring
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Hva ønsker du?
      description: Beskriv funksjonen eller forbedringen du ser for deg.
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Hvilket problem løser det?
      description: Fortell gjerne om situasjonen der dette ville vært nyttig.
    validations:
      required: false
